- name: Build docker image
  community.docker.docker_image_build:
    name: meetTrack_image
    force_source: true
    source: build
    path: "{{ APP_PATH }}"
    dockerfile: .docker/Dockerfile

- name: Run docker container
  community.docker.docker_container:
    name: meetTrack
    image: meetTrack_image
    recreate: true
    restart: true
    ports:
      - "{{ PORT }}:{{ PORT }}"
    env:
      NODE_ENV: "{{ NODE_ENV }}"
