- name: Build docker image
  community.docker.docker_image:
    build:
      path: "{{ APP_PATH }}/.docker/"
    name: meettrack_image
    source: build
    force_source: true
    args:
      chdir: "/home/ubuntu/apps/app"

- name: Run docker container
  community.docker.docker_container:
    name: meettrack
    image: meettrack_image
    recreate: true
    restart: true
    env_file: /home/ubuntu/app.env
    ports:
      - "{{ PORT }}:{{ PORT }}"
    env:
      NODE_ENV: "{{ NODE_ENV }}"
