name: Build and deploy MeetTrack server

on:
  push:
    branches: [ci]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: steelkiwi/ansible:5.10.0
    steps:
      - uses: actions/checkout@v4
        name: Checkout 🛎️

      - name: Run ansible
        env:
          repo: ${{ github.repository }}
          server: ${{ secrets.AWS }}
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - 
          export ANSIBLE_CONFIG=$(eval echo `readlink -f ansible/ansible.cfg`)
          cd ansible && ansible-playbook deploy.yml --extra-vars="image=meettrack |
                                                                           host=${{ env.server }}
                                                                           branch=ci
                                                                           repo=${{ env.repo }}
                                                                           playbook=production.yml
                                                                           project_name=meettrack
                                                                           
